import{describe,expect,it}from"vitest";import{readFileSync}from"node:fs";import{join}from"node:path"
const sql=readFileSync(join(process.cwd(),"supabase/migrations/20260812560000_recorrencia_disponibilidade.sql"),"utf8")
const detalhe=readFileSync(join(process.cwd(),"supabase/migrations/20260812570000_detalhar_disponibilidade_agenda.sql"),"utf8")
const semDemo=readFileSync(join(process.cwd(),"supabase/migrations/20260812580000_excluir_demo_fluxos_operacionais.sql"),"utf8")
describe("recorrência e disponibilidade da agenda",()=>{
 it("calcula disponibilidade como expediente menos bloqueios e compromissos",()=>{expect(sql).toContain("exists(select 1 from public.disponibilidades_profissional");expect(sql).toContain("not exists(select 1 from public.indisponibilidades_profissional");expect(sql).toContain("not exists(select 1 from public.agendamentos");expect(sql).toContain("'nao_configurada'");expect(sql).toContain("'fora_expediente'")})
 it("cria séries com frequências e limites explícitos",()=>{expect(sql).toContain("'semanal','quinzenal','tres_semanas','mensal'");expect(sql).toContain("v_num<105");expect(sql).toContain("+730");expect(sql).toContain("p_conflitos not in('bloquear','ignorar')")})
 it("serializa e valida cada ocorrência no backend",()=>{expect(sql.match(/pg_advisory_xact_lock/g)?.length).toBeGreaterThanOrEqual(2);expect(sql).toContain("not public.horario_disponivel");expect(sql).toContain("paciente_id=p_paciente_id");expect(sql).toContain("series_conflict")})
 it("mantém escrita somente por funções autorizadas e auditadas",()=>{expect(sql).not.toMatch(/create policy (series_agendamentos|indisponibilidades)_(insert|update|delete)/);expect(sql).toContain("revoke all on table public.series_agendamentos");expect(sql).toContain("revoke all on function public.horario_disponivel");expect(sql).toContain("SERIE_AGENDAMENTOS_CRIADA");expect(sql).toContain("INDISPONIBILIDADE_CRIADA")})
 it("explica conflitos sem revelar dados do paciente agendado",()=>{expect(detalhe).toContain("Expediente semanal não cadastrado");expect(detalhe).toContain("Expediente do dia:");expect(detalhe).toContain("Ocupado:");expect(detalhe).toContain("Bloqueio:");expect(detalhe).not.toContain("paciente_nome");expect(detalhe).not.toContain("finalidade")})
 it("isola o cenário demo dos fluxos administrativos",()=>{expect(semDemo).toContain("demo@registrosaba.local");expect(semDemo).toContain("not public.paciente_demonstracao(p.id)");expect(semDemo).toContain("not public.usuario_demonstracao(pr.id)");expect(semDemo).toContain("agendamentos_bloquear_demo");expect(semDemo).toContain("ocorrencias_frequencia_bloquear_demo")})
})
