import Link from "next/link"
import { AlertCircle, ArrowRight, CalendarDays, ClipboardList, Target, UserRoundPlus, Users } from "lucide-react"
import { getPainelCoordenacaoAgregado, getPainelProfissionalAgregado, getProfile } from "@/lib/registros/queries"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

export default async function DashboardPage() {
  const profile=await getProfile()
  if(profile?.papel==="coordenacao")return <PainelCoordenacao/>
  const painel=await getPainelProfissionalAgregado()
  if(!painel)return <div className="rounded-2xl border border-dashed p-8 text-sm text-muted-foreground">Aplique a migration do painel agregado para visualizar o resumo operacional.</div>
  const pacientesResumo=painel.pacientes,recentes=painel.sessoes_recentes
  const formatar = (data: string) => new Date(`${data}T12:00:00`).toLocaleDateString("pt-BR")
  const cards = [
    ["Pacientes ativos", painel.totais.pacientes_ativos, Users],
    ["Sessões no mês", painel.totais.sessoes_mes, CalendarDays],
    ["Alvos ativos", painel.totais.alvos_ativos, Target],
    ["Solicitações pendentes", painel.totais.solicitacoes_pendentes, AlertCircle],
    ["Configurações pendentes", painel.totais.configuracoes_pendentes, ClipboardList],
  ] as const

  return <div className="flex flex-col gap-6">
    <div><h1 className="text-2xl font-bold">Painel</h1><p className="mt-1 text-sm text-muted-foreground">Resumo operacional dos pacientes vinculados a você.</p></div>
    {painel.proximo_compromisso&&<Card className="border-primary/30"><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-primary">Próximo paciente</p><p className="font-bold">{painel.proximo_compromisso.paciente_nome}</p><p className="text-sm text-muted-foreground">{new Date(painel.proximo_compromisso.inicio).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})}</p></div><Button asChild><Link href="/registros/agenda">Ver agenda <ArrowRight className="size-4"/></Link></Button></CardContent></Card>}
    {painel.totais.solicitacoes_pendentes > 0 && <Card className="border-primary/30 bg-primary/5"><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-primary text-primary-foreground"><UserRoundPlus className="size-4" /></div><div><p className="font-bold">{painel.totais.solicitacoes_pendentes === 1 ? "1 solicitação de acesso pendente" : `${painel.totais.solicitacoes_pendentes} solicitações de acesso pendentes`}</p><p className="text-sm text-muted-foreground">Revise as solicitações recebidas para aprovar ou negar o vínculo.</p></div></div><Link href="/registros/solicitacoes" className="inline-flex shrink-0 items-center gap-1 text-sm font-semibold text-primary">Ver solicitações <ArrowRight className="size-3.5" /></Link></CardContent></Card>}
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(([label, valor, Icon]) => <Card key={label}><CardContent className="p-4"><Icon className="mb-2 size-4 text-primary" /><p className="text-2xl font-bold">{valor}</p><p className="text-xs text-muted-foreground">{label}</p></CardContent></Card>)}</section>
    <section><div className="mb-3 flex items-end justify-between"><div><h2 className="text-lg font-bold">Seus pacientes</h2><p className="text-sm text-muted-foreground">Até 12 pacientes ativos; consulte a lista para visualizar todos.</p></div><Link href="/registros/pacientes" className="text-sm font-semibold text-primary">Ver lista</Link></div>{pacientesResumo.length === 0 ? <div className="rounded-2xl border border-dashed p-8 text-center text-sm text-muted-foreground">Nenhum paciente vinculado.</div> : <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{pacientesResumo.map((item) => <Link key={item.id} href={`/registros/pacientes/${item.id}`}><Card className="h-full transition-colors hover:border-primary/40"><CardContent className="p-5"><h3 className="truncate font-bold">{item.nome}</h3><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><span className="text-xs text-muted-foreground">Alvos ativos</span><p className="font-bold">{item.alvos_ativos}</p></div><div><span className="text-xs text-muted-foreground">Sessões no mês</span><p className="font-bold">{item.sessoes_mes}</p></div></div><p className="mt-4 text-xs text-muted-foreground">Última sessão: {item.ultima_sessao ? formatar(item.ultima_sessao) : "sem sessões"}</p></CardContent></Card></Link>)}</div>}</section>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ClipboardList className="size-4 text-primary" />Sessões recentes</CardTitle></CardHeader><CardContent className="space-y-3">{recentes.length === 0 ? <p className="text-sm text-muted-foreground">Nenhuma sessão registrada.</p> : recentes.map((s) => <Link key={s.id} href={`/registros/pacientes/${s.paciente_id}/sessoes`} className="flex items-center justify-between gap-3 rounded-xl border p-3 hover:bg-muted"><div className="min-w-0"><p className="truncate text-sm font-semibold">{s.paciente_nome}</p><p className="truncate text-xs text-muted-foreground">{s.contexto} · {formatar(s.data)}</p></div><Badge variant="secondary">{s.alvos} alvos</Badge></Link>)}<Link href="/registros/sessoes" className="inline-flex items-center gap-1 text-sm font-semibold text-primary">Ver histórico <ArrowRight className="size-3.5" /></Link></CardContent></Card>
  </div>
}

async function PainelCoordenacao(){const painel=await getPainelCoordenacaoAgregado(),proximo=painel?.proximo;return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Painel operacional</h1><p className="mt-1 text-sm text-muted-foreground">Agenda, cadastros e pendências da coordenação.</p></div><section className="grid gap-3 sm:grid-cols-3"><Card><CardContent className="p-4"><CalendarDays className="mb-2 size-4 text-primary"/><p className="text-2xl font-bold">{painel?.compromissos_7_dias??0}</p><p className="text-xs text-muted-foreground">Compromissos nos próximos 7 dias</p></CardContent></Card><Card><CardContent className="p-4"><Users className="mb-2 size-4 text-primary"/><p className="text-2xl font-bold">{painel?.pacientes_ativos??0}</p><p className="text-xs text-muted-foreground">Pacientes ativos</p></CardContent></Card><Card><CardContent className="p-4"><AlertCircle className="mb-2 size-4 text-primary"/><p className="text-2xl font-bold">{painel?.pacientes_sem_profissional??0}</p><p className="text-xs text-muted-foreground">Pacientes sem profissional vinculado</p></CardContent></Card></section><Card><CardHeader><CardTitle className="text-base">Próximo atendimento</CardTitle></CardHeader><CardContent>{proximo?<div><p className="font-bold">{proximo.paciente_nome}</p><p className="text-sm text-muted-foreground">{proximo.profissional_nome} · {new Date(proximo.inicio).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})}</p>{!proximo.pode_iniciar&&<p className="mt-1 text-xs text-amber-700">Aguardando o profissional aceitar o paciente.</p>}</div>:<p className="text-sm text-muted-foreground">Nenhum atendimento futuro nos próximos 7 dias.</p>}</CardContent></Card><div className="flex gap-3"><Button asChild><Link href="/registros/agenda">Abrir agenda <ArrowRight className="size-4"/></Link></Button><Button asChild variant="secondary"><Link href="/registros/pacientes/novo">Cadastrar paciente</Link></Button></div></div>}
