import Link from "next/link"
import { CalendarDays, CalendarPlus, Clock3, List, Rows3 } from "lucide-react"
import { getAgendamentos, getDisponibilidadesAgenda, getOpcoesAgenda, getProfile, getProfissoes } from "@/lib/registros/queries"
import { AgendaOperacional } from "@/components/registros/agenda-operacional"
import { AgendaTimeline } from "@/components/registros/agenda-timeline"
import { DisponibilidadeForm } from "@/components/registros/disponibilidade-form"
import { IndisponibilidadeForm } from "@/components/registros/indisponibilidade-form"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"

function dataValida(v?: string) { const d = v && /^\d{4}-\d{2}-\d{2}$/.test(v) ? new Date(`${v}T12:00:00`) : new Date(); return Number.isNaN(d.getTime()) ? new Date() : d }

export default async function AgendaPage({ searchParams }: { searchParams: Promise<{ data?: string; visao?: string; secao?: string; formato?: string; destaque?: string }> }) {
  const q = await searchParams, profile = await getProfile()
  if (!profile) return null
  const referencia = dataValida(q.data), referenciaTexto = referencia.toLocaleDateString("en-CA"), formato = q.formato === "timeline" ? "timeline" : "lista", visao = q.visao === "dia" || q.visao === "semana" ? q.visao : formato === "timeline" ? "semana" : "dia", secao = profile.papel === "profissional" ? "agenda" : q.secao === "disponibilidade" ? "disponibilidade" : "agenda", inicio = new Date(referencia)
  if (visao === "semana") inicio.setDate(inicio.getDate() - inicio.getDay())
  inicio.setHours(0, 0, 0, 0)
  const fim = new Date(inicio); fim.setDate(fim.getDate() + (visao === "dia" ? 1 : 7))
  const [agendamentos, opcoes, disponibilidades, profissoes] = await Promise.all([secao === "agenda" ? getAgendamentos(inicio.toISOString(), fim.toISOString()) : Promise.resolve([]), profile.papel === "profissional" ? Promise.resolve(null) : getOpcoesAgenda(), secao === "disponibilidade" || formato === "timeline" ? getDisponibilidadesAgenda() : Promise.resolve([]), profile.papel === "profissional" ? Promise.resolve([]) : getProfissoes()])
  const abas = profile.papel === "profissional" ? [["agenda", "/registros/agenda", "Compromissos", CalendarDays]] as const : [["agenda", "/registros/agenda", "Compromissos", CalendarDays], ["disponibilidade", "/registros/agenda?secao=disponibilidade", "Disponibilidade", Clock3]] as const

  return <div className="space-y-6"><div className="flex items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Agenda</h1><p className="mt-1 text-sm text-muted-foreground">Consulte compromissos ou configure quando cada pessoa atende.</p></div>{profile.papel !== "profissional" && <Button asChild size="icon" className="shrink-0 sm:!h-9 sm:!w-auto sm:px-4"><Link href="/registros/agenda/novo" aria-label="Novo agendamento" title="Novo agendamento"><CalendarPlus className="size-4" /><span className="hidden sm:inline">Novo agendamento</span></Link></Button>}</div>
    {profile.papel !== "profissional" && <nav aria-label="Áreas da agenda" className="mobile-tab-scroll -mx-3 overflow-x-auto px-3 pb-1 sm:-mx-4 sm:px-4 lg:mx-0 lg:px-0"><div className="flex min-w-max gap-1 rounded-xl border bg-card p-1">{abas.map(([valor, href, label, Icon]) => <Link key={valor} href={href} aria-current={secao === valor ? "page" : undefined} className={cn("flex min-h-11 snap-start items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold transition-colors md:min-h-0", secao === valor ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground")}><Icon className="size-4" />{label}</Link>)}</div></nav>}
    {secao === "agenda" ? <div className="space-y-4"><nav aria-label="Formato da agenda" className="mobile-tab-scroll -mx-3 overflow-x-auto px-3 pb-1 sm:-mx-4 sm:px-4 lg:mx-0 lg:px-0"><div className="flex min-w-max gap-1 rounded-xl border bg-card p-1"><Link href={`/registros/agenda?data=${referenciaTexto}&visao=dia&formato=lista`} className={cn("flex min-h-11 items-center justify-center gap-1.5 rounded-lg px-3 py-2 text-sm font-semibold transition-colors md:min-h-0", formato === "lista" ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground")}><List className="size-4" />Lista</Link><Link href={`/registros/agenda?data=${referenciaTexto}&visao=semana&formato=timeline`} className={cn("flex min-h-11 items-center justify-center gap-1.5 rounded-lg px-3 py-2 text-sm font-semibold transition-colors md:min-h-0", formato === "timeline" ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground")}><Rows3 className="size-4" />Linha do tempo</Link></div></nav>{formato === "timeline" ? <AgendaTimeline agendamentos={agendamentos} disponibilidades={disponibilidades} opcoes={opcoes} profissoes={profissoes} papel={profile.papel} referencia={referenciaTexto} visao={visao} /> : <AgendaOperacional agendamentos={agendamentos} opcoes={opcoes} profissoes={profissoes} papel={profile.papel} usuarioId={profile.id} referencia={referenciaTexto} visao={visao} destaqueId={q.destaque} />}</div> : <div className="space-y-4"><div className="rounded-2xl border border-primary/20 bg-primary/5 p-4"><h2 className="font-semibold">Como a disponibilidade é calculada?</h2><p className="mt-1 text-sm text-muted-foreground">Expediente configurado menos os bloqueios e compromissos existentes. Sem expediente cadastrado, a pessoa aparece como disponibilidade não configurada.</p></div><DisponibilidadeForm registros={disponibilidades} opcoes={opcoes} profissoes={profissoes} papel={profile.papel} usuarioId={profile.id} /><IndisponibilidadeForm opcoes={opcoes} profissoes={profissoes} papel={profile.papel} usuarioId={profile.id} /></div>}
  </div>
}
