"use client"
import{Bar,BarChart,CartesianGrid,Legend,Line,LineChart,XAxis,YAxis}from"recharts"
import{analisarEvolucaoTentativas,type PontoSerieClinica}from"@/lib/registros/clinico/serie-clinica"
import{ChartContainer,ChartTooltip}from"@/components/ui/chart"
const formatar=(data:string)=>new Date(`${data}T12:00:00`).toLocaleDateString("pt-BR").slice(0,5)
const tendencia=(v:string,positivo:"aumentou"|"reduziu")=>v==="dados_insuficientes"?"Dados insuficientes":v==="estavel"?"Estável":v===positivo?"Evolução favorável":"Requer análise"
export function AnaliseTentativas({pontos}:{pontos:PontoSerieClinica[]}){
 const detalhados=pontos.filter(p=>p.tentativas);if(!detalhados.length)return null
 const totais=detalhados.reduce((a,p)=>{const t=p.tentativas!;a.total+=t.total;a.independentes+=t.independentes;a.corretasComAjuda+=t.corretasComAjuda;a.comAjuda+=t.comAjuda;a.incorretas+=t.incorretas;a.semResposta+=t.semResposta;for(const[n,q]of Object.entries(t.ajudas))a.ajudas[n]+=q;return a},{total:0,independentes:0,corretasComAjuda:0,comAjuda:0,incorretas:0,semResposta:0,ajudas:{gestual:0,verbal:0,modelo:0,fisica_parcial:0,fisica_total:0}as Record<string,number>})
 const pct=(v:number)=>totais.total?Math.round(v/totais.total*100):0;const evolucao=analisarEvolucaoTentativas(pontos)
 const dados=detalhados.map(p=>({data:p.data,independente:p.tentativas!.independentes,corretaComAjuda:p.tentativas!.corretasComAjuda,incorreta:p.tentativas!.incorretas,semResposta:p.tentativas!.semResposta,latencia:p.tentativas!.latenciaMedia}));const predominante=Object.entries(totais.ajudas).sort((a,b)=>b[1]-a[1])[0];const nomes:Record<string,string>={gestual:"Gestual",verbal:"Verbal",modelo:"Modelo",fisica_parcial:"Física parcial",fisica_total:"Física total"}
 return <section className="space-y-5 rounded-2xl border p-4"><div><h3 className="font-semibold">Independência e níveis de ajuda</h3><p className="text-xs text-muted-foreground">Leitura descritiva das sessões com tentativas detalhadas; não substitui interpretação clínica.</p></div><div className="grid gap-3 sm:grid-cols-4"><Resumo label="Independentes" valor={`${pct(totais.independentes)}%`}/><Resumo label="Corretas com ajuda" valor={`${pct(totais.corretasComAjuda)}%`}/><Resumo label="Incorretas" valor={`${pct(totais.incorretas)}%`}/><Resumo label="Ajuda mais usada" valor={predominante?.[1]?nomes[predominante[0]]:"Nenhuma"}/></div><div className="grid gap-3 sm:grid-cols-3"><Leitura label="Independência recente" valor={tendencia(evolucao.independencia,"aumentou")}/><Leitura label="Necessidade de ajuda" valor={tendencia(evolucao.ajuda,"reduziu")}/><Leitura label="Latência média" valor={tendencia(evolucao.latencia,"reduziu")}/></div><ChartContainer config={{independente:{label:"Correta independente",color:"#0891b2"},corretaComAjuda:{label:"Correta com ajuda",color:"#f59e0b"},incorreta:{label:"Incorreta",color:"#ef4444"},semResposta:{label:"Sem resposta",color:"#94a3b8"}}} className="h-72 w-full aspect-auto"><BarChart data={dados}><CartesianGrid vertical={false}/><XAxis dataKey="data" tickFormatter={formatar}/><YAxis allowDecimals={false}/><ChartTooltip/><Legend/><Bar dataKey="independente" stackId="t" fill="var(--color-independente)"/><Bar dataKey="corretaComAjuda" stackId="t" fill="var(--color-corretaComAjuda)"/><Bar dataKey="incorreta" stackId="t" fill="var(--color-incorreta)"/><Bar dataKey="semResposta" stackId="t" fill="var(--color-semResposta)" radius={[4,4,0,0]}/></BarChart></ChartContainer>{dados.some(d=>d.latencia!==null)&&<div><p className="mb-2 text-sm font-semibold">Latência média por sessão</p><ChartContainer config={{latencia:{label:"Latência média",color:"#6366f1"}}} className="h-56 w-full aspect-auto"><LineChart data={dados}><CartesianGrid vertical={false}/><XAxis dataKey="data" tickFormatter={formatar}/><YAxis unit="s"/><ChartTooltip/><Line dataKey="latencia" stroke="var(--color-latencia)" strokeWidth={3} connectNulls={false}/></LineChart></ChartContainer></div>}<div className="flex flex-wrap gap-2 text-xs text-muted-foreground">{Object.entries(totais.ajudas).map(([n,q])=><span key={n} className="rounded-full bg-muted px-3 py-1">{nomes[n]}: {q}</span>)}<span className="rounded-full bg-muted px-3 py-1">Cobertura: {evolucao.cobertura} sessão(ões) recentes</span></div></section>
}
function Resumo({label,valor}:{label:string;valor:string}){return <div className="rounded-xl bg-muted p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-bold">{valor}</p></div>};function Leitura({label,valor}:{label:string;valor:string}){return <div className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{valor}</p></div>}
