"use client"
import{useMemo,useState}from"react";import type{CapacitacaoAplicador,PlanoClinicoCompleto,RegistroValidadeSocial,SessaoClinicaComRegistros,SolicitacaoConcordancia}from"@/lib/registros/clinico/modelo";import{construirSerieClinica,resumirSerie}from"@/lib/registros/clinico/serie-clinica";import{avaliarDominio}from"@/lib/registros/clinico/decisao-dominio";import{GraficoSerieClinica}from"@/components/registros/grafico-serie-clinica";import{AnaliseTentativas}from"@/components/registros/analise-tentativas";import{ComparacaoContextual}from"@/components/registros/comparacao-contextual";import{ProntidaoRevisao}from"@/components/registros/prontidao-revisao";import{QualidadeDados}from"@/components/registros/qualidade-dados";import{Badge}from"@/components/ui/badge";import{Card,CardContent,CardHeader,CardTitle}from"@/components/ui/card";import{Select,SelectContent,SelectItem,SelectTrigger,SelectValue}from"@/components/ui/select"
const todos="todos",faseLabel:Record<string,string>={linha_de_base:"Linha de base",ensino:"Ensino",generalizacao:"Generalização",manutencao:"Manutenção"}
export function AnaliseAlvosClinicos({planos,sessoes,profissionalAtualId,validadeSocial,concordancias,capacitacoes}:{planos:PlanoClinicoCompleto[];sessoes:SessaoClinicaComRegistros[];profissionalAtualId:string;validadeSocial:RegistroValidadeSocial[];concordancias:SolicitacaoConcordancia[];capacitacoes:CapacitacaoAplicador[]}){
 const alvos=useMemo(()=>planos.flatMap(p=>p.objetivos.flatMap(o=>o.alvos)).filter(a=>a.profissional_id===profissionalAtualId),[planos,profissionalAtualId]),[alvoId,setAlvoId]=useState(alvos[0]?.id??""),[periodo,setPeriodo]=useState(todos),[fase,setFase]=useState(todos),[ambiente,setAmbiente]=useState(todos),[aplicador,setAplicador]=useState(todos),alvo=alvos.find(a=>a.id===alvoId)
 const serieCompleta=useMemo(()=>alvo?construirSerieClinica(alvo,sessoes):null,[alvo,sessoes]),serie=useMemo(()=>{if(!serieCompleta)return null;const limite=periodo===todos?null:new Date(new Date().setMonth(new Date().getMonth()-Number(periodo))).toISOString().slice(0,10);return{...serieCompleta,pontos:serieCompleta.pontos.filter(p=>(!limite||p.data>=limite)&&(fase===todos||p.fase===fase)&&(ambiente===todos||p.ambiente===ambiente)&&(aplicador===todos||p.aplicador===aplicador))}},[serieCompleta,periodo,fase,ambiente,aplicador]),criterio=alvo?[...alvo.criterios].sort((a,b)=>b.versao-a.versao)[0]:undefined,dominio=criterio&&alvo?avaliarDominio(criterio,alvo.id,sessoes):null,resumo=serie?resumirSerie(serie.pontos,serie.direcao):null
 if(!alvos.length)return null;const ambientes=[...new Set(serieCompleta?.pontos.map(p=>p.ambiente).filter(Boolean)??[])]as string[],aplicadores=[...new Set(serieCompleta?.pontos.map(p=>p.aplicador).filter(Boolean)??[])]as string[]
 return <Card><CardHeader><CardTitle className="text-base">Evolução por alvo clínico</CardTitle></CardHeader><CardContent className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Filtro label="Alvo" value={alvoId} set={setAlvoId} itens={alvos.map(a=>[a.id,a.nome])}/><Filtro label="Período" value={periodo} set={setPeriodo} itens={[["3","3 meses"],["6","6 meses"],["12","12 meses"],[todos,"Todo o histórico"]]}/><Filtro label="Fase" value={fase} set={setFase} itens={[[todos,"Todas"],...["linha_de_base","ensino","generalizacao","manutencao"].map(v=>[v,faseLabel[v]])]}/><Filtro label="Ambiente" value={ambiente} set={setAmbiente} itens={[[todos,"Todos"],...ambientes.map(v=>[v,v])]}/><Filtro label="Aplicador" value={aplicador} set={setAplicador} itens={[[todos,"Todos"],...aplicadores.map(v=>[v,v])]}/></div>{serie&&<><div className="grid gap-3 sm:grid-cols-4"><Resumo label="Unidade" valor={serie.unidade}/><Resumo label="Primeiro registro" valor={resumo?.primeiro??"—"}/><Resumo label="Último registro" valor={resumo?.ultimo??"—"}/><Resumo label="Variação" valor={resumo?.variacao===null||resumo?.variacao===undefined?"—":`${resumo.variacao>0?"+":""}${resumo.variacao}`}/></div><GraficoSerieClinica serie={serie}/><AnaliseTentativas pontos={serie.pontos}/><ComparacaoContextual pontos={serie.pontos} unidade={serie.unidade}/>{alvo&&<><QualidadeDados alvo={alvo} pontos={serieCompleta?.pontos??[]} concordancias={concordancias} capacitacoes={capacitacoes} profissionalAtualId={profissionalAtualId}/><ProntidaoRevisao alvo={alvo} sessoes={sessoes} validadeSocial={validadeSocial} profissionalAtualId={profissionalAtualId}/></>}</>}{dominio&&<div className="rounded-xl border p-4"><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold">Apoio à decisão clínica</p><Badge variant={dominio.estado==="criterio_atingido"?"default":"secondary"}>{dominio.estado==="criterio_atingido"?"Parâmetro atingido":dominio.estado==="sem_dados"?"Sem dados":"Em progresso"}</Badge></div><p className="text-sm text-muted-foreground">{dominio.mensagem}</p></div>}<p className="text-xs text-muted-foreground">A unidade e o tipo de gráfico são definidos pela medida. Filtros não alteram o dado original nem misturam alvos incompatíveis.</p></CardContent></Card>
}
function Filtro({label,value,set,itens}:{label:string;value:string;set:(v:string)=>void;itens:string[][]}){return <label className="space-y-2"><span className="text-sm font-semibold">{label}</span><Select value={value} onValueChange={set}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{itens.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label>}
function Resumo({label,valor}:{label:string;valor:string|number}){return <div className="rounded-xl bg-muted p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-bold">{valor}</p></div>}
