"use client"
import{useState}from"react";import{Check,Copy,Link2,ShieldOff}from"lucide-react";import{criarAcessoResponsavel,revogarAcessoResponsavel}from"@/lib/registros/actions";import type{AcessoResponsavel}from"@/lib/registros/responsavel/types";import{calcularStatusAcesso}from"@/lib/registros/responsavel/status-acesso";import{Badge}from"@/components/ui/badge";import{Button}from"@/components/ui/button";import{Checkbox}from"@/components/ui/checkbox";import{Input}from"@/components/ui/input";import{Label}from"@/components/ui/label";import{Select,SelectContent,SelectItem,SelectTrigger,SelectValue}from"@/components/ui/select"
const cfgPadrao={periodo_meses:12,alvo_ids:[]as string[],exibir_criterios:true,exibir_fases:true,exibir_integridade:false,exibir_contextos:false,exibir_analise_tentativas:false}
export function CompartilhamentoResponsavel({pacienteId,acessos,alvos}:{pacienteId:string;acessos:AcessoResponsavel[];alvos:{id:string;nome:string;proprio:boolean}[]}){
 const[locais,setLocais]=useState(acessos);const[validade,setValidade]=useState("30");const[escopo,setEscopo]=useState<"profissional"|"equipe">("profissional");const[descricao,setDescricao]=useState("Responsável");const[cfg,setCfg]=useState(cfgPadrao);const[novoLink,setNovoLink]=useState<string|null>(null);const[copiado,setCopiado]=useState(false);const[processando,setProcessando]=useState(false);const[erro,setErro]=useState("");const formatar=(d:string)=>new Date(d).toLocaleString("pt-BR")
 function marcarAlvo(id:string,v:boolean){setCfg(c=>({...c,alvo_ids:v?[...new Set([...c.alvo_ids,id])]:c.alvo_ids.filter(x=>x!==id)}))}
 async function gerar(){setProcessando(true);setErro("");setNovoLink(null);const r=await criarAcessoResponsavel({pacienteId,descricao,escopo,validadeDias:validade==="sem_prazo"?null:Number(validade)as 7|30|90,periodoMeses:cfg.periodo_meses as 3|6|12|24,alvoIds:cfg.alvo_ids,exibirCriterios:cfg.exibir_criterios,exibirFases:cfg.exibir_fases,exibirIntegridade:cfg.exibir_integridade,exibirContextos:cfg.exibir_contextos,exibirAnaliseTentativas:cfg.exibir_analise_tentativas});if(r&&"error"in r)setErro(r.error);else if(r&&"acesso"in r){setNovoLink(`${window.location.origin}/acompanhamento/${r.acesso.token}`);const agora=new Date().toISOString();setLocais(xs=>[{id:r.acesso.id,descricao:descricao.trim()||"Responsável",criado_em:r.acesso.criado_em,expira_em:r.acesso.expira_em,revogado_em:null,ultimo_acesso_em:null,ativo:true,escopo,configuracao:cfg},...xs.map(a=>calcularStatusAcesso(a)==="ativo"?{...a,ativo:false,revogado_em:agora}:a)])}setProcessando(false)}
 async function copiar(){if(!novoLink)return;await navigator.clipboard.writeText(novoLink);setCopiado(true);setTimeout(()=>setCopiado(false),2500)}async function revogar(id:string){setProcessando(true);const r=await revogarAcessoResponsavel({acessoId:id,pacienteId});if(r&&"error"in r)setErro(r.error);else setLocais(xs=>xs.map(a=>a.id===id?{...a,ativo:false,revogado_em:new Date().toISOString()}:a));setProcessando(false)}
 const ativos=locais.filter(a=>calcularStatusAcesso(a)==="ativo"),encerrados=locais.filter(a=>calcularStatusAcesso(a)!=="ativo")
 function render(a:AcessoResponsavel){const ativo=calcularStatusAcesso(a)==="ativo",c=a.configuracao??cfgPadrao;return <div key={a.id} className="flex flex-col gap-3 rounded-xl border p-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><p className="text-sm font-semibold">{a.descricao}</p><Badge variant={ativo?"outline":"secondary"}>{ativo?"Ativo":a.revogado_em?"Revogado":"Expirado"}</Badge></div><div className="mt-2 grid gap-x-5 gap-y-1 text-xs text-muted-foreground sm:grid-cols-3"><span>Criado: {formatar(a.criado_em)}</span><span>Expira: {a.expira_em?formatar(a.expira_em):"Sem prazo"}</span><span>Šltimo acesso: {a.ultimo_acesso_em?formatar(a.ultimo_acesso_em):"Nunca"}</span></div><p className="mt-2 text-xs text-muted-foreground">{a.escopo==="equipe"?"Equipe":"Meus dados"} · {c.periodo_meses??12} meses · {c.alvo_ids?.length?`${c.alvo_ids.length} alvo(s) selecionado(s)`:"todos os alvos permitidos"}</p></div>{ativo&&<Button size="sm" variant="outline" disabled={processando} onClick={()=>revogar(a.id)}><ShieldOff className="size-4"/>Revogar</Button>}</div>}
 return <section className="flex flex-col gap-5 rounded-2xl border bg-card p-5"><div><h2 className="flex items-center gap-2 text-lg font-bold"><Link2 className="size-5 text-primary"/>Compartilhamento com responsáveis</h2><p className="text-sm text-muted-foreground">O link é somente leitura e nunca inclui observações privadas ou registros ABC.</p></div>
 <div className="grid gap-4 rounded-xl bg-muted/40 p-4"><div className="grid gap-3 sm:grid-cols-3"><div><Label>Identificação</Label><Input className="mt-2" value={descricao} onChange={e=>setDescricao(e.target.value)} maxLength={80}/></div><div><Label>Dados</Label><Select value={escopo} onValueChange={v=>{setEscopo(v as typeof escopo);setCfg(c=>({...c,alvo_ids:[]}))}}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="profissional">Somente meus registros</SelectItem><SelectItem value="equipe">Equipe vinculada</SelectItem></SelectContent></Select></div><div><Label>Período clínico</Label><Select value={String(cfg.periodo_meses)} onValueChange={v=>setCfg(c=>({...c,periodo_meses:Number(v)}))}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent>{[3,6,12,24].map(v=><SelectItem key={v} value={String(v)}>{v} meses</SelectItem>)}</SelectContent></Select></div></div>
 <div><Label>Alvos compartilhados</Label><p className="mb-2 text-xs text-muted-foreground">Sem seleção, todos os alvos permitidos pelo escopo serão incluídos.</p><div className="grid gap-2 sm:grid-cols-2">{alvos.filter(a=>escopo==="equipe"||a.proprio).map(a=><label key={a.id} className="flex items-center gap-2 rounded-lg border bg-card p-2 text-sm"><Checkbox checked={cfg.alvo_ids.includes(a.id)} onCheckedChange={v=>marcarAlvo(a.id,v===true)}/>{a.nome}{!a.proprio&&<span className="ml-auto text-xs text-muted-foreground">equipe</span>}</label>)}</div></div>
 <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{[["exibir_criterios","Critérios"],["exibir_fases","Fases clínicas"],["exibir_integridade","Integridade do protocolo"],["exibir_contextos","Ambiente e aplicador"],["exibir_analise_tentativas","Independência e ajudas"]].map(([k,l])=><label key={k} className="flex items-center gap-2 text-sm"><Checkbox checked={Boolean(cfg[k as keyof typeof cfg])} onCheckedChange={v=>setCfg(c=>({...c,[k]:v===true}))}/>{l}</label>)}</div>
 <div className="flex flex-col gap-3 sm:flex-row sm:items-end"><div className="w-full sm:max-w-48"><Label>Validade do link</Label><Select value={validade} onValueChange={setValidade}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="7">7 dias</SelectItem><SelectItem value="30">30 dias</SelectItem><SelectItem value="90">90 dias</SelectItem><SelectItem value="sem_prazo">Sem prazo</SelectItem></SelectContent></Select></div><Button onClick={gerar} disabled={processando}>Gerar acesso</Button></div></div>
 {novoLink&&<div className="rounded-xl border border-primary/30 bg-primary/5 p-4"><p className="text-sm font-semibold">Copie este link agora</p><p className="mt-1 text-xs text-muted-foreground">Por segurança, ele não poderá ser recuperado depois.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><Input readOnly value={novoLink}/><Button onClick={copiar} className="shrink-0">{copiado?<Check className="size-4"/>:<Copy className="size-4"/>}{copiado?"Link copiado":"Copiar link"}</Button></div></div>}{erro&&<p className="text-sm text-destructive">{erro}</p>}<div className="space-y-3"><h3 className="text-sm font-semibold">Acesso externo ativo</h3>{ativos.length?ativos.map(render):<p className="text-sm text-muted-foreground">Nenhum acesso externo ativo.</p>}</div>{encerrados.length>0&&<details className="rounded-xl border p-4"><summary className="cursor-pointer text-sm font-semibold">Acessos revogados e expirados ({encerrados.length})</summary><div className="mt-3 space-y-3">{encerrados.map(render)}</div></details>}</section>
}


