"use client"
import { useState, type FormEvent } from "react"
import { useRouter } from "next/navigation"
import { ShieldCheck } from "lucide-react"
import { criarPlanoApoioComportamental } from "@/lib/registros/actions"
import type { PlanoClinicoCompleto, SessaoClinicaComRegistros } from "@/lib/registros/clinico/modelo"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"

const funcoes: Record<string,string> = { indeterminada: "Indeterminada", atencao: "Atenção", fuga_esquiva: "Fuga/esquiva", acesso_tangivel: "Acesso a tangível", automatica: "Automática", multipla: "Múltipla" }
type Campos = { justificativa: string; antecedentes: string; substitutivo: string; ensino: string; consequentes: string; seguranca: string; revisao: string }
function FormPlano({ pacienteId, alvoId, fechar }: { pacienteId: string; alvoId: string; fechar: () => void }) { const router=useRouter(); const [funcao,setFuncao]=useState("indeterminada"); const [campos,setCampos]=useState<Campos>({justificativa:"",antecedentes:"",substitutivo:"",ensino:"",consequentes:"",seguranca:"",revisao:""}); const [erro,setErro]=useState(""); const [salvando,setSalvando]=useState(false); const campo=(chave:keyof Campos,label:string,obrigatorio=true)=><div className="space-y-2"><Label>{label}</Label><Textarea value={campos[chave]} onChange={(e)=>setCampos((c)=>({...c,[chave]:e.target.value}))} required={obrigatorio} minLength={obrigatorio?(chave==="justificativa"?10:3):undefined}/></div>; async function salvar(e:FormEvent){e.preventDefault();setSalvando(true);setErro("");const r=await criarPlanoApoioComportamental({pacienteId,alvoId,funcaoAssumida:funcao,justificativaFuncional:campos.justificativa,estrategiasAntecedentes:campos.antecedentes,comportamentoSubstitutivo:campos.substitutivo,procedimentoEnsinoSubstitutivo:campos.ensino,estrategiasConsequentes:campos.consequentes,planoSeguranca:campos.seguranca||null,criteriosRevisao:campos.revisao});if(r&&"error" in r)setErro(r.error);else{fechar();router.refresh()}setSalvando(false)} return <form onSubmit={salvar} className="space-y-4 rounded-xl border p-4"><div className="space-y-2"><Label>Função assumida pelo profissional</Label><Select value={funcao} onValueChange={setFuncao}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(funcoes).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div>{campo("justificativa","Justificativa baseada nos dados")}<div className="grid gap-4 sm:grid-cols-2">{campo("antecedentes","Estratégias antecedentes")}{campo("substitutivo","Comportamento substitutivo")}{campo("ensino","Ensino do comportamento substitutivo")}{campo("consequentes","Estratégias consequentes")}{campo("seguranca","Plano de segurança, quando aplicável",false)}{campo("revisao","Critérios e prazo de revisão")}</div>{erro&&<p className="text-sm text-destructive">{erro}</p>}<div className="flex gap-2"><Button disabled={salvando}>{salvando?"Salvando...":"Salvar nova versão"}</Button><Button type="button" variant="ghost" onClick={fechar}>Cancelar</Button></div></form> }

export function PlanosApoioComportamental({ pacienteId, profissionalAtualId, planos, sessoes }: { pacienteId:string; profissionalAtualId:string; planos:PlanoClinicoCompleto[]; sessoes:SessaoClinicaComRegistros[] }) { const [editando,setEditando]=useState<string|null>(null); const alvos=planos.flatMap((p)=>p.objetivos.flatMap((o)=>o.alvos)).filter((a)=>a.profissional_id===profissionalAtualId&&a.natureza==="reducao"); if(!alvos.length)return null; return <section className="space-y-4"><div><h2 className="flex items-center gap-2 text-lg font-bold"><ShieldCheck className="size-5 text-primary"/>Apoio comportamental</h2><p className="text-sm text-muted-foreground">Planos versionados, baseados em observações e decisão clínica explícita.</p></div>{alvos.map((alvo)=>{const atual=[...alvo.planos_apoio].sort((a,b)=>b.versao-a.versao)[0];const observacoes=sessoes.flatMap((s)=>s.observacoes_abc).filter((o)=>o.alvo_id===alvo.id);const contagens=observacoes.reduce<Record<string,number>>((acc,o)=>{const k=o.funcao_hipotese??"sem hipótese";acc[k]=(acc[k]??0)+1;return acc},{});return <Card key={alvo.id}><CardHeader><div className="flex flex-wrap justify-between gap-2"><CardTitle className="text-base">{alvo.nome}</CardTitle><Badge variant="secondary">{observacoes.length} observações ABC</Badge></div></CardHeader><CardContent className="space-y-4">{Object.keys(contagens).length>0&&<p className="text-xs text-muted-foreground">Distribuição descritiva: {Object.entries(contagens).map(([k,v])=>`${funcoes[k]??k}: ${v}`).join(" · ")}. Isso não confirma função.</p>}{atual?<div className="grid gap-2 text-sm sm:grid-cols-2"><p><strong>Função assumida:</strong> {funcoes[atual.funcao_assumida]}</p><p><strong>Versão:</strong> {atual.versao}</p><p><strong>Substitutivo:</strong> {atual.comportamento_substitutivo}</p><p><strong>Revisão:</strong> {atual.criterios_revisao}</p><p className="sm:col-span-2"><strong>Justificativa:</strong> {atual.justificativa_funcional}</p></div>:<p className="text-sm text-muted-foreground">Nenhum plano configurado.</p>}{editando===alvo.id?<FormPlano pacienteId={pacienteId} alvoId={alvo.id} fechar={()=>setEditando(null)}/>:<Button size="sm" variant="outline" onClick={()=>setEditando(alvo.id)}>{atual?"Nova versão":"Configurar plano"}</Button>}</CardContent></Card>})}</section> }
