"use client"

import { useState } from "react"
import { Award, Heart, Sparkles } from "lucide-react"
import { CartesianGrid, Line, LineChart, XAxis, YAxis } from "recharts"
import type { SharedPatientDashboard } from "@/lib/registros/responsavel/types"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { ChartContainer, ChartTooltip } from "@/components/ui/chart"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"

const formatar = (data: string) => new Date(`${data}T12:00:00`).toLocaleDateString("pt-BR")

export function PortalResponsavel({ dados }: { dados: SharedPatientDashboard & { serieGeral: { data: string; percentual: number; avaliacoes: number }[] } }) {
  const [selecionada, setSelecionada] = useState(dados.habilidades[0]?.nome ?? "")
  const habilidade = dados.habilidades.find((h) => h.nome === selecionada)
  const adquiridas = dados.habilidades.filter((h) => h.status === "adquirida")
  return <main className="min-h-screen bg-background">
    <header className="border-b bg-card"><div className="mx-auto max-w-5xl px-4 py-5 flex items-center gap-3"><div className="size-10 rounded-full bg-primary text-primary-foreground flex items-center justify-center"><Heart className="size-5" /></div><div><p className="font-bold">Acompanhamento</p><p className="text-xs text-muted-foreground">Uma visão simples da evolução</p></div></div></header>
    <div className="mx-auto max-w-5xl px-4 py-6 sm:py-10 flex flex-col gap-6">
      <section><p className="text-sm text-muted-foreground">Acompanhamento de</p><h1 className="text-3xl font-bold">{dados.primeiroNome}</h1><p className="text-sm text-muted-foreground mt-2">Período de {formatar(dados.periodoInicio)} a {formatar(dados.periodoFim)} · Última atualização: {dados.ultimaAtualizacao ? formatar(dados.ultimaAtualizacao) : "ainda sem registros"}</p></section>
      <section className="grid grid-cols-1 sm:grid-cols-3 gap-3"><Card><CardContent className="p-5"><Sparkles className="size-5 text-primary mb-3" /><p className="text-2xl font-bold">{dados.habilidades.length}</p><p className="text-sm text-muted-foreground">Habilidades acompanhadas</p></CardContent></Card><Card><CardContent className="p-5"><Award className="size-5 text-primary mb-3" /><p className="text-2xl font-bold">{adquiridas.length}</p><p className="text-sm text-muted-foreground">Conquistas identificadas</p></CardContent></Card><Card><CardContent className="p-5"><Heart className="size-5 text-primary mb-3" /><p className="text-2xl font-bold">{dados.progressoGeral === null ? "Sem dados" : `${dados.progressoGeral}%`}</p><p className="text-sm text-muted-foreground">Evolução recente</p></CardContent></Card></section>
      <Card><CardHeader><CardTitle className="text-lg">Evolução geral</CardTitle></CardHeader><CardContent>{dados.serieGeral.length === 0 ? <p className="py-16 text-center text-sm text-muted-foreground">Ainda não há dados suficientes para apresentar a evolução.</p> : <ChartContainer config={{ percentual: { label: "Evolução", color: "var(--primary)" } }} className="h-64 sm:h-80 w-full aspect-auto"><LineChart data={dados.serieGeral} margin={{ left: 0, right: 12 }}><CartesianGrid vertical={false} /><XAxis dataKey="data" tickFormatter={(v) => formatar(v).slice(0, 5)} /><YAxis domain={[0, 100]} width={38} tickFormatter={(v) => `${v}%`} /><ChartTooltip formatter={(value, _name, item) => <div className="grid gap-1"><strong>{value}%</strong><span>{formatar(item.payload.data)}</span></div>} /><Line dataKey="percentual" stroke="var(--color-percentual)" strokeWidth={3} dot={{ r: 4 }} /></LineChart></ChartContainer>}</CardContent></Card>
      <Card><CardHeader><CardTitle className="text-lg">Evolução por habilidade</CardTitle></CardHeader><CardContent className="space-y-5"><Select value={selecionada} onValueChange={setSelecionada}><SelectTrigger className="w-full sm:max-w-sm"><SelectValue placeholder="Selecione uma habilidade" /></SelectTrigger><SelectContent>{dados.habilidades.map((h) => <SelectItem key={h.nome} value={h.nome}>{h.nome}</SelectItem>)}</SelectContent></Select>{!habilidade || habilidade.avaliacoes.length === 0 ? <p className="py-12 text-center text-sm text-muted-foreground">Ainda não há dados suficientes para apresentar a evolução desta habilidade.</p> : <><div><p className="font-semibold">{habilidade.nome}</p><p className="text-sm text-muted-foreground">{habilidade.progresso === null ? "Evolução ainda não calculável" : `Evolução recente: ${habilidade.progresso}%`}</p></div><ChartContainer config={{ valor: { label: habilidade.nome, color: "var(--primary)" } }} className="h-64 sm:h-72 w-full aspect-auto"><LineChart data={habilidade.avaliacoes} margin={{ left: 0, right: 12 }}><CartesianGrid vertical={false} /><XAxis dataKey="data" tickFormatter={(v) => formatar(v).slice(0, 5)} /><YAxis domain={[0, 1]} ticks={[0, 0.5, 0.7, 1]} width={30} tickFormatter={(v) => v === 1 ? "A" : v === 0.7 ? "B+" : v === 0.5 ? "B-" : "C"} /><ChartTooltip formatter={(value, _name, item) => <div className="grid gap-1"><strong>{item.payload.codigo}</strong><span>{formatar(item.payload.data)}</span></div>} /><Line dataKey="valor" stroke="var(--color-valor)" strokeWidth={3} dot={{ r: 4 }} /></LineChart></ChartContainer></>}</CardContent></Card>
      <Card><CardHeader><CardTitle className="text-lg flex gap-2"><Award className="size-5 text-primary" />Conquistas recentes</CardTitle></CardHeader><CardContent className="space-y-3">{adquiridas.length === 0 ? <p className="text-sm text-muted-foreground">As conquistas aparecerão aqui conforme houver registros suficientes.</p> : adquiridas.sort((a, b) => (b.adquiridaEm ?? "").localeCompare(a.adquiridaEm ?? "")).map((h) => <div key={h.nome} className="rounded-xl bg-muted p-4"><p className="font-semibold">✓ {h.nome}</p><p className="text-sm text-muted-foreground">{h.adquiridaEm && `Conquista registrada em ${formatar(h.adquiridaEm)}`}</p></div>)}</CardContent></Card>
      <p className="rounded-2xl border border-primary/20 bg-primary/5 p-4 text-sm text-muted-foreground">As informações apresentadas representam registros de acompanhamento e devem ser interpretadas em conjunto com o profissional responsável.</p>
    </div>
  </main>
}
