"use client"

import Link from "next/link"
import { SlidersHorizontal } from "lucide-react"
import type { Profissao } from "@/lib/registros/types"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet"

export function UsuariosFiltros({ busca, profissao, papel, status, profissoes }: { busca: string; profissao: string; papel: string; status: string; profissoes: Profissao[] }) {
  const ativos = Number(Boolean(busca)) + Number(Boolean(profissao)) + Number(papel !== "todos") + Number(status !== "todos")
  const campos = <><Campo label="Nome ou e-mail"><Input name="busca" defaultValue={busca} placeholder="Buscar usuário..." /></Campo><Campo label="Profissão"><select name="profissao" defaultValue={profissao} className="h-11 w-full rounded-md border border-input bg-card px-3 text-base md:h-9 md:text-sm"><option value="">Todas</option>{profissoes.map((item) => <option key={item.id} value={item.id}>{item.nome}{!item.ativo ? " (inativa)" : ""}</option>)}</select></Campo><Campo label="Papel"><select name="papel" defaultValue={papel} className="h-11 w-full rounded-md border border-input bg-card px-3 text-base md:h-9 md:text-sm"><option value="todos">Todos</option><option value="profissional">Profissional</option><option value="coordenacao">Coordenação</option><option value="admin">Administrador</option></select></Campo><Campo label="Status"><select name="status" defaultValue={status} className="h-11 w-full rounded-md border border-input bg-card px-3 text-base md:h-9 md:text-sm"><option value="todos">Todos</option><option value="ativo">Ativo</option><option value="inativo">Inativo</option></select></Campo></>
  return <><div className="flex items-center gap-2 md:hidden"><Sheet><SheetTrigger asChild><Button variant="secondary" className="relative"><SlidersHorizontal className="size-4" />Filtros{ativos > 0 && <span className="flex size-5 items-center justify-center rounded-full bg-primary text-[11px] font-bold text-primary-foreground">{ativos}</span>}</Button></SheetTrigger><SheetContent side="bottom" className="max-h-[85vh] overflow-y-auto rounded-t-2xl bg-card"><SheetHeader><SheetTitle>Filtrar usuários</SheetTitle><SheetDescription>Busque e refine a equipe cadastrada.</SheetDescription></SheetHeader><form action="/registros/usuarios" className="space-y-4 px-4 pb-5">{campos}<div className="grid grid-cols-2 gap-2"><Button type="button" variant="secondary" asChild><Link href="/registros/usuarios">Limpar</Link></Button><Button>Aplicar</Button></div></form></SheetContent></Sheet>{ativos > 0 && <span className="text-xs text-muted-foreground">{ativos} filtro(s) ativo(s)</span>}</div><form action="/registros/usuarios" className="hidden items-end gap-3 rounded-2xl border bg-card p-4 md:grid md:grid-cols-2 xl:grid-cols-[minmax(220px,1fr)_220px_180px_160px_auto]">{campos}<Button>Aplicar filtros</Button></form></>
}
function Campo({ label, children }: { label: string; children: React.ReactNode }) { return <label className="space-y-2 text-sm font-medium"><span className="block">{label}</span>{children}</label> }
