import Link from "next/link"
import { Activity, ArrowRight, CalendarDays, ClipboardCheck, ClipboardList, Target } from "lucide-react"
import { getCenarioDemonstracao } from "@/lib/registros/queries"
import { formatarData } from "@/lib/registros/demonstracao"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

export default async function DemonstracaoPacientePage({params}:{params:Promise<{id:string}>}){
 const{id}=await params;const dados=await getCenarioDemonstracao();if(!dados)return null
 const alvos=dados.planos.flatMap((p)=>p.objetivos.flatMap((o)=>o.alvos));const ultima=[...dados.sessoes].sort((a,b)=>b.data.localeCompare(a.data))[0]
 const atalhos=[["Avaliação","Evidências e síntese inicial",ClipboardCheck,"avaliacao"],["Sessões","Histórico das coletas",ClipboardList,"sessoes"],["Planejamento","Planos, objetivos e alvos",Target,"planejamento"],["Análise","Evolução dos resultados",Activity,"analise"],["Participação","Validade social",CalendarDays,"participacao"]]as const
 return <div className="space-y-6"><section className="grid gap-3 sm:grid-cols-3"><Card><CardContent className="p-4"><Target className="mb-2 size-4 text-primary"/><p className="text-2xl font-bold">{alvos.length}</p><p className="text-xs text-muted-foreground">Alvos ativos</p></CardContent></Card><Card><CardContent className="p-4"><CalendarDays className="mb-2 size-4 text-primary"/><p className="text-lg font-bold">{ultima?formatarData(ultima.data):"—"}</p><p className="text-xs text-muted-foreground">Última sessão</p></CardContent></Card><Card><CardContent className="p-4"><ClipboardList className="mb-2 size-4 text-primary"/><p className="text-2xl font-bold">{dados.sessoes.length}</p><p className="text-xs text-muted-foreground">Sessões no período</p></CardContent></Card></section><section><h2 className="mb-3 text-lg font-bold">Áreas de trabalho</h2><div className="grid gap-3 sm:grid-cols-2">{atalhos.map(([titulo,desc,Icon,rota])=><Link key={rota} href={`/registros/demonstracao/pacientes/${id}/${rota}`}><Card className="h-full hover:bg-muted/40"><CardContent className="flex items-center gap-4 p-5"><div className="rounded-xl bg-primary/10 p-3"><Icon className="size-5 text-primary"/></div><div className="flex-1"><p className="font-bold">{titulo}</p><p className="text-sm text-muted-foreground">{desc}</p></div><ArrowRight className="size-4 text-muted-foreground"/></CardContent></Card></Link>)}</div></section>{ultima&&<Card><CardHeader><CardTitle className="text-base">Última sessão</CardTitle></CardHeader><CardContent><p className="mb-3 text-sm text-muted-foreground">{ultima.contexto}</p><div className="flex flex-wrap gap-2">{ultima.registros.map((r)=><Badge key={r.id} variant="secondary">{r.alvo_nome}</Badge>)}</div></CardContent></Card>}</div>
}
