-- Frequencia interativa: agregados completos e somente uma pagina de lancamentos.
create or replace function public.relatorio_frequencia_paginado(p_inicio date,p_fim date,p_profissional_id uuid default null,p_paciente_id uuid default null,p_limite integer default 20,p_offset integer default 0)
returns jsonb language plpgsql stable security definer set search_path='' set row_security=off as $$declare v_registros jsonb;v_profissionais jsonb;v_pacientes jsonb;v_resumo jsonb;v_total bigint;begin
 if not public.usuario_ativo()or p_inicio is null or p_fim is null or p_fim<p_inicio or p_fim-p_inicio>370 then raise exception'invalid_report'using errcode='22023';end if;
 if not public.usuario_tem_permissao('frequencia.visualizar_equipe')then p_profissional_id:=auth.uid();end if;
 select count(*),jsonb_build_object('ocorrencias',count(*),'faltas',count(*)filter(where o.tipo like'falta_%'),'justificadas',count(*)filter(where o.tipo='falta_justificada'),'nao_justificadas',count(*)filter(where o.tipo='falta_nao_justificada'),'cancelamentos',count(*)filter(where o.tipo like'cancelamento_%'))into v_total,v_resumo from public.ocorrencias_frequencia o where o.cancelado_em is null and o.data_ocorrencia between p_inicio and p_fim and(p_profissional_id is null or o.profissional_id=p_profissional_id)and(p_paciente_id is null or o.paciente_id=p_paciente_id);
 select coalesce(jsonb_agg(x order by(x->>'data_ocorrencia')desc,(x->>'created_at')desc),'[]'::jsonb)into v_registros from(select jsonb_build_object('id',o.id,'paciente_id',o.paciente_id,'paciente_nome',p.nome_completo,'profissional_id',o.profissional_id,'profissional_nome',pr.nome,'agendamento_id',o.agendamento_id,'agendamento_inicio',a.inicio,'agendamento_fim',a.fim,'data_ocorrencia',o.data_ocorrencia,'tipo',o.tipo,'motivo',o.motivo,'observacao_administrativa',o.observacao_administrativa,'criado_por',o.criado_por,'created_at',o.created_at)x from public.ocorrencias_frequencia o join public.pacientes p on p.id=o.paciente_id join public.profiles pr on pr.id=o.profissional_id left join public.agendamentos a on a.id=o.agendamento_id where o.cancelado_em is null and o.data_ocorrencia between p_inicio and p_fim and(p_profissional_id is null or o.profissional_id=p_profissional_id)and(p_paciente_id is null or o.paciente_id=p_paciente_id)order by o.data_ocorrencia desc,o.created_at desc limit least(greatest(p_limite,1),50)offset greatest(p_offset,0))s;
 select coalesce(jsonb_agg(x order by(x->>'total')::integer desc),'[]'::jsonb)into v_profissionais from(select jsonb_build_object('id',pr.id,'nome',pr.nome,'total',count(*),'justificadas',count(*)filter(where o.tipo='falta_justificada'),'nao_justificadas',count(*)filter(where o.tipo='falta_nao_justificada'),'cancelamentos',count(*)filter(where o.tipo like'cancelamento_%'))x from public.ocorrencias_frequencia o join public.profiles pr on pr.id=o.profissional_id where o.cancelado_em is null and o.data_ocorrencia between p_inicio and p_fim and(p_profissional_id is null or o.profissional_id=p_profissional_id)and(p_paciente_id is null or o.paciente_id=p_paciente_id)group by pr.id,pr.nome)s;
 select coalesce(jsonb_agg(x order by(x->>'total_faltas')::integer desc),'[]'::jsonb)into v_pacientes from(select jsonb_build_object('id',p.id,'nome',p.nome_completo,'total_faltas',count(*)filter(where o.tipo like'falta_%'),'justificadas',count(*)filter(where o.tipo='falta_justificada'),'nao_justificadas',count(*)filter(where o.tipo='falta_nao_justificada'))x from public.ocorrencias_frequencia o join public.pacientes p on p.id=o.paciente_id where o.cancelado_em is null and o.data_ocorrencia between p_inicio and p_fim and(p_profissional_id is null or o.profissional_id=p_profissional_id)and(p_paciente_id is null or o.paciente_id=p_paciente_id)group by p.id,p.nome_completo)s;
 return jsonb_build_object('registros',v_registros,'profissionais',v_profissionais,'pacientes',v_pacientes,'resumo',v_resumo,'total_registros',v_total);end$$;
revoke all on function public.relatorio_frequencia_paginado(date,date,uuid,uuid,integer,integer)from public;
grant execute on function public.relatorio_frequencia_paginado(date,date,uuid,uuid,integer,integer)to authenticated;
create index if not exists ocorrencias_frequencia_ativas_data_idx on public.ocorrencias_frequencia(data_ocorrencia desc,created_at desc)where cancelado_em is null;
notify pgrst,'reload schema';
