-- Detalhamento opcional de tentativas e niveis de ajuda, reconciliado ao agregado.
create table if not exists public.tentativas_individuais(id uuid primary key default gen_random_uuid(),registro_medicao_id uuid not null references public.registros_medicao(id)on delete restrict,profissional_id uuid not null references public.profiles(id)on delete restrict,ordem integer not null check(ordem>0),resultado text not null check(resultado in('correta','incorreta','sem_resposta')),nivel_ajuda text not null check(nivel_ajuda in('independente','gestual','verbal','modelo','fisica_parcial','fisica_total')),latencia_segundos numeric check(latencia_segundos is null or latencia_segundos>=0),observacao text,created_at timestamptz not null default now(),unique(registro_medicao_id,ordem));
create index if not exists tentativas_registro_ordem_idx on public.tentativas_individuais(registro_medicao_id,ordem);alter table public.tentativas_individuais enable row level security;alter table public.tentativas_individuais force row level security;
drop policy if exists tentativas_select on public.tentativas_individuais;create policy tentativas_select on public.tentativas_individuais for select to authenticated using(profissional_id=auth.uid()and exists(select 1 from public.registros_medicao r join public.sessoes_clinicas s on s.id=r.sessao_id where r.id=registro_medicao_id and s.profissional_id=auth.uid()));
create or replace function public.registrar_sessao_clinica_v6(p_paciente_id uuid,p_data date,p_contexto text,p_observacoes_privadas text,p_registros jsonb,p_ambiente_tipo text,p_aplicador_tipo text,p_integridade jsonb,p_observacoes_abc jsonb,p_finalidade text,p_tentativas jsonb default'[]')returns uuid language plpgsql security definer set search_path='pg_catalog','public' set row_security=off as $$
declare v_id uuid;v_grupo jsonb;v_item jsonb;v_registro public.registros_medicao%rowtype;v_total integer;v_independentes integer;
begin if jsonb_typeof(coalesce(p_tentativas,'[]'))<>'array'then raise exception'invalid_trials'using errcode='22023';end if;v_id:=public.registrar_sessao_clinica_v5(p_paciente_id,p_data,p_contexto,p_observacoes_privadas,p_registros,p_ambiente_tipo,p_aplicador_tipo,p_integridade,p_observacoes_abc,p_finalidade);
for v_grupo in select value from jsonb_array_elements(coalesce(p_tentativas,'[]'))loop select r.*into v_registro from public.registros_medicao r where r.sessao_id=v_id and r.alvo_id=(v_grupo->>'alvo_id')::uuid;if not found or v_registro.tipo_medicao not in('tentativas_discretas','percentual_oportunidades')or jsonb_typeof(v_grupo->'itens')<>'array'then raise exception'invalid_trials'using errcode='22023';end if;v_total:=jsonb_array_length(v_grupo->'itens');select count(*)into v_independentes from jsonb_array_elements(v_grupo->'itens')i where i->>'resultado'='correta'and i->>'nivel_ajuda'='independente';if v_total<>(v_registro.dados->>'oportunidades')::integer or v_independentes<>(v_registro.dados->>'respostas_independentes')::integer then raise exception'trials_summary_mismatch'using errcode='22023';end if;
for v_item in select value from jsonb_array_elements(v_grupo->'itens')loop if(v_item->>'ordem')::integer<1 or v_item->>'resultado'not in('correta','incorreta','sem_resposta')or v_item->>'nivel_ajuda'not in('independente','gestual','verbal','modelo','fisica_parcial','fisica_total')or(nullif(v_item->>'latencia_segundos','')is not null and(v_item->>'latencia_segundos')::numeric<0)then raise exception'invalid_trials'using errcode='22023';end if;insert into public.tentativas_individuais(registro_medicao_id,profissional_id,ordem,resultado,nivel_ajuda,latencia_segundos,observacao)values(v_registro.id,auth.uid(),(v_item->>'ordem')::integer,v_item->>'resultado',v_item->>'nivel_ajuda',nullif(v_item->>'latencia_segundos','')::numeric,nullif(trim(v_item->>'observacao'),''));end loop;end loop;return v_id;exception when unique_violation or invalid_text_representation then raise exception'invalid_trials'using errcode='22023';end $$;
revoke execute on function public.registrar_sessao_clinica_v5(uuid,date,text,text,jsonb,text,text,jsonb,jsonb,text)from authenticated;revoke all on function public.registrar_sessao_clinica_v6(uuid,date,text,text,jsonb,text,text,jsonb,jsonb,text,jsonb)from public;grant execute on function public.registrar_sessao_clinica_v6(uuid,date,text,text,jsonb,text,text,jsonb,jsonb,text,jsonb)to authenticated;notify pgrst,'reload schema';
