alter table public.profiles add column if not exists profissao text,add column if not exists conselho_tipo text,add column if not exists conselho_numero text,add column if not exists conselho_uf text,add column if not exists foto_zoom numeric not null default 1,add column if not exists foto_pos_x numeric not null default 0,add column if not exists foto_pos_y numeric not null default 0;
alter table public.pacientes add column if not exists foto_zoom numeric not null default 1,add column if not exists foto_pos_x numeric not null default 0,add column if not exists foto_pos_y numeric not null default 0;
alter table public.profiles drop constraint if exists profiles_dados_profissionais_check;
alter table public.profiles add constraint profiles_dados_profissionais_check check(
  length(coalesce(profissao,'')) <= 100 and
  length(coalesce(conselho_tipo,'')) <= 30 and
  length(coalesce(conselho_numero,'')) <= 40 and
  (conselho_uf is null or conselho_uf ~ '^[A-Z]{2}$')
);
alter table public.profiles drop constraint if exists profiles_foto_enquadramento_check;
alter table public.profiles add constraint profiles_foto_enquadramento_check check(foto_zoom between 1 and 2.5 and foto_pos_x between -50 and 50 and foto_pos_y between -50 and 50);
alter table public.pacientes drop constraint if exists pacientes_foto_enquadramento_check;
alter table public.pacientes add constraint pacientes_foto_enquadramento_check check(foto_zoom between 1 and 2.5 and foto_pos_x between -50 and 50 and foto_pos_y between -50 and 50);

create or replace function public.atualizar_minha_foto(p_foto_path text,p_zoom numeric default 1,p_pos_x numeric default 0,p_pos_y numeric default 0)returns void language plpgsql security definer set search_path='pg_catalog','public' set row_security=off as $$begin if auth.uid()is null or not public.usuario_ativo()then raise exception'unauthorized'using errcode='42501';end if;if p_foto_path is not null and p_foto_path!~('^profiles/'||auth.uid()::text||'/[0-9]+\.(jpg|png|webp)$')then raise exception'invalid_photo_path'using errcode='22023';end if;if p_zoom not between 1 and 2.5 or p_pos_x not between-50 and 50 or p_pos_y not between-50 and 50 then raise exception'invalid_photo_crop'using errcode='22023';end if;update public.profiles set foto_path=p_foto_path,foto_zoom=p_zoom,foto_pos_x=p_pos_x,foto_pos_y=p_pos_y where id=auth.uid();end$$;
create or replace function public.atualizar_foto_paciente(p_paciente_id uuid,p_foto_path text,p_zoom numeric default 1,p_pos_x numeric default 0,p_pos_y numeric default 0)returns void language plpgsql security definer set search_path='pg_catalog','public' set row_security=off as $$begin if not public.usuario_ativo()or not public.usuario_vinculado(p_paciente_id)then raise exception'unauthorized'using errcode='42501';end if;if p_foto_path is not null and p_foto_path!~('^patients/'||p_paciente_id::text||'/[0-9]+\.(jpg|png|webp)$')then raise exception'invalid_photo_path'using errcode='22023';end if;if p_zoom not between 1 and 2.5 or p_pos_x not between-50 and 50 or p_pos_y not between-50 and 50 then raise exception'invalid_photo_crop'using errcode='22023';end if;update public.pacientes set foto_path=p_foto_path,foto_zoom=p_zoom,foto_pos_x=p_pos_x,foto_pos_y=p_pos_y where id=p_paciente_id;end$$;
revoke all on function public.atualizar_minha_foto(text)from public,authenticated;revoke all on function public.atualizar_foto_paciente(uuid,text)from public,authenticated;
revoke all on function public.atualizar_minha_foto(text,numeric,numeric,numeric)from public;grant execute on function public.atualizar_minha_foto(text,numeric,numeric,numeric)to authenticated;
revoke all on function public.atualizar_foto_paciente(uuid,text,numeric,numeric,numeric)from public;grant execute on function public.atualizar_foto_paciente(uuid,text,numeric,numeric,numeric)to authenticated;

create or replace function public.atualizar_meus_dados_profissionais(p_profissao text,p_conselho_tipo text,p_conselho_numero text,p_conselho_uf text)returns void language plpgsql security definer set search_path='pg_catalog','public' set row_security=off as $$begin if auth.uid()is null or not public.usuario_ativo()then raise exception'unauthorized'using errcode='42501';end if;if length(coalesce(p_profissao,''))>100 or length(coalesce(p_conselho_tipo,''))>30 or length(coalesce(p_conselho_numero,''))>40 or(p_conselho_uf is not null and p_conselho_uf!~'^[A-Z]{2}$')then raise exception'invalid_professional_data'using errcode='22023';end if;update public.profiles set profissao=nullif(trim(p_profissao),''),conselho_tipo=nullif(upper(trim(p_conselho_tipo)),''),conselho_numero=nullif(trim(p_conselho_numero),''),conselho_uf=nullif(upper(trim(p_conselho_uf)),'')where id=auth.uid();end$$;
revoke all on function public.atualizar_meus_dados_profissionais(text,text,text,text)from public;grant execute on function public.atualizar_meus_dados_profissionais(text,text,text,text)to authenticated;

drop function if exists public.profissionais_vinculados_paciente(uuid);create function public.profissionais_vinculados_paciente(p_paciente_id uuid)returns table(id uuid,nome text,foto_path text,foto_zoom numeric,foto_pos_x numeric,foto_pos_y numeric,profissao text,conselho_tipo text,conselho_numero text,conselho_uf text)language sql stable security definer set search_path=''as $$select p.id,p.nome,p.foto_path,p.foto_zoom,p.foto_pos_x,p.foto_pos_y,p.profissao,p.conselho_tipo,p.conselho_numero,p.conselho_uf from public.paciente_psicologos pp join public.profiles p on p.id=pp.psicologo_id and p.status='ativo'where pp.paciente_id=p_paciente_id and(public.usuario_admin()or public.usuario_vinculado(p_paciente_id))order by p.nome$$;revoke all on function public.profissionais_vinculados_paciente(uuid)from public;grant execute on function public.profissionais_vinculados_paciente(uuid)to authenticated;notify pgrst,'reload schema';
