export * from "./escala"
export * from "./tipos"
export * from "./calcular-progresso"
export * from "./verificar-aquisicao"
export * from "./calcular-tendencia"
export * from "./calcular-status"
export * from "./calcular-progresso-geral"
export * from "./analytics"
